[package]
name = "rgh"
version = "0.1.0"
authors = ["k-nasa <htilcs1115@gmail.com>"]
description = "Creates GitHub release and upload asset files"
readme = "README"
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
