name: Release

on:
  pull_request:
  create:
    tags:
      - v*.*.*
env:
  BIN_NAME: grh
  MISC: README.md LICENSE

jobs:
  cross_compile:
    name: Cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@master

      - name: Install cross
        run: |
          rustup default nightly
          rustup self update
          rustup target add ${{ matrix.target }}
          cargo install --force cross

      - name: cross build
        run: |
          cross build --target ${{ matrix.target }} --release

      - name: build release package
        run: |
          bin=${BIN_NAME}
          # winのときは.exeがいるので環境変数をセットしなおす
          if [[ ${{matrix.target}} = "x86_64-pc-windows-gnu" ]]; then bin=${BIN_NAME}.exe; fi
          DIRNAME=${BIN_NAME}_${{matrix.target}}
          mkdir ${DIRNAME}
          cp ./target/${{matrix.target}}/release/$bin $DIRNAME
          cp $MISC $DIRNAME
          mkdir dist
          tar czf dist/$DIRNAME.tar.gz $DIRNAME
